config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  resources :recipes do
    member do
      patch :toggle_public
    end
    resources :recipe_foods, only: [:new, :create, :destroy]
  end

  resources :foods, only: [:index, :show, :new, :create, :destroy]
  resources :public_recipes, only: [:index]

  resources :shopping_lists, only: [:index] do
    collection do
      get 'generate'
    end
  end

  get 'public_recipes_custom', to: 'recipes#public_recipes', as: 'public_recipes_custom'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true, length: { minimum: 2, maximum: 50 }, allow_blank: false
  validates :measurement_unit, presence: true, allow_blank: false
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }

  def name_with_measurement_unit
    "#{name} (#{measurement_unit})"
  end
end

app/models/recipe.rb
# app/models/recipe.rb

class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true, length: { minimum: 1, maximum: 50 }, allow_blank: false
  validates :preparation_time, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :cooking_time, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :description, presence: true, allow_blank: false
  validates :public, inclusion: { in: [true, false] }

  def preparation_time_hours
    hours = preparation_time / 60
    hours.to_i
  end

  def preparation_time_minutes
    minutes = preparation_time % 60
    minutes.to_i
  end

  def cooking_time_hours
    hours = cooking_time / 60
    hours.to_i
  end

  def cooking_time_minutes
    minutes = cooking_time % 60
    minutes.to_i
  end

  def total_time_hours
    total = preparation_time + cooking_time
    hours = total / 60
    hours.to_i
  end

  def total_time_minutes
    total = preparation_time + cooking_time
    minutes = total % 60
    minutes.to_i
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true, numericality: { greater_than: 0 }

  def total_price
    food.price * quantity
  end

  def quantity_needed
    [quantity - food.quantity, 0].max
  end

  def total_price_need
    food.price * quantity_needed
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :foods, dependent: :destroy
  has_many :recipes, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :current_user
  def after_sign_in_path_for(_resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @foods = Food.includes(:user).all
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user = current_user

    if @food.save
      redirect_to foods_path, notice: 'Ingredient was successfully created.'
    else
      redirect_to new_food_path, alert: 'Cannot create a new ingredient.'
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy

    redirect_to foods_path, notice: 'Food successfully deleted.'
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @foods = Food.all.order(id: :desc)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @recipes = Recipe.where(public: true).order(created_at: :desc)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe = Recipe.includes(:recipe_foods).find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.new
  end

  def create
    @recipe = Recipe.includes(:recipe_foods).find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.new(recipe_foods_params)

    if @recipe_food.save
      redirect_to recipe_path(@recipe), notice: 'Add new ingredient'
    else
      redirect_to new_recipe_recipe_food_path(@recipe.id)
    end
  end

  def destroy
    @recipe = Recipe.includes(:recipe_foods).find(params[:recipe_id])
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy!

    redirect_to recipe_path(@recipe.id), notice: 'Ingredient successfully deleted'
  end

  private

  def recipe_foods_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipes = current_user.recipes
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = @recipe.recipe_foods.includes(:food)
    @preparation_time_hours = @recipe.preparation_time_hours
    @preparation_time_minutes = @recipe.preparation_time_minutes
    @cooking_time_hours = @recipe.cooking_time_hours
    @cooking_time_minutes = @recipe.cooking_time_minutes
  end

  def toggle_public
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: !@recipe.public)
    redirect_to @recipe, notice: "Recipe is now #{@recipe.public ? 'public' : 'private'}"

    # if @recipe.update(public: !@recipe.public)
    #   render json: { public: @recipe.public }
    # else
    #   render json: { errors: @recipe.errors.full_messages }, status: :unprocessable_entity
    # end
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    @recipe.preparation_time = calculate_minutes(params[:recipe][:preparation_time_hr],
                                                 params[:recipe][:preparation_time_min])
    @recipe.cooking_time = calculate_minutes(params[:recipe][:cooking_time_hr], params[:recipe][:cooking_time_min])

    if @recipe.save
      redirect_to @recipe, notice: 'Recipe successfully created.'
    else
      render 'new', alert: 'Failed to create a new recipe.'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy!

    redirect_to recipes_path, notice: 'Recipe successfully deleted.'
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :public)
  end

  def calculate_minutes(hours, minutes)
    (hours.to_i * 60) + minutes.to_i
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  def index
    recipe_id = params[:recipe_id]
    return unless recipe_id.present?

    # Fetch Recipe
    @recipe = Recipe.find_by(id: recipe_id)
    return redirect_to root_path, alert: 'Recipe not found' unless @recipe

    # Fetch User Foods
    @foods = current_user.foods

    @recipe_foods = @recipe.recipe_foods.includes(:food)

    @needed_money = @recipe_foods.sum { |recipe_food| recipe_food.food.price * recipe_food.quantity }
  end

  def generate
    recipe_id = params[:recipe_id]
    return redirect_to root_path, alert: 'Recipe not found' unless Recipe.exists?(recipe_id)

    redirect_to shopping_lists_path(recipe_id:)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/index.html.erb
<main class="container mt-3">
  <div class="card">
    <% if user_signed_in? %>
      <div class="card-header">
        <div class="col-12">
          <%= link_to 'Add food', new_food_path, class: 'btn btn-primary mb-3 float-end' %>
        </div>
      </div>
    <% end %>
    <div class="card-body">
      <% if @foods.present? %>
        <small class="text text-success small">
          Total number of foods:
          <%= @foods.size %>
        </small>
      <% else %>
        <small class="text text-danger small">
          No foods found.
        </small>
      <% end %>
      <table class="table table-striped table-bordered table-hover">
        <thead class="table-dark">
          <tr>
            <th>Food</th>
            <th>Measurement unit</th>
            <th>Unit price (in INR)</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @foods.each do |food| %>
            <tr>
              <td><%= food.name %></td>
              <td><%= food.measurement_unit %></td>
              <td>&#x20b9; <%= food.price %></td>
              <% if user_signed_in? %>
              <td>
                <%= button_to "Delete",
                  food_path(food),
                  method: :delete,
                  data: { 
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  },
                  class: 'btn btn-link' %>
              </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</main>

app/views/foods/new.html.erb
<!-- app/views/foods/new.html.erb -->

<main class="container mt-3">
  <div class="card">
    <div class="card-header">
      <div class="col-12">
        <h2>Add Food</h2>
      </div>
    </div>
    <div class="card-body">
      <%= form_for @food do |f| %>
        <div class="mb-3">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="mb-3">
          <%= f.label :measurement_unit %>
          <%= f.text_field :measurement_unit, class: 'form-control' %>
        </div>

        <div class="mb-3">
          <%= f.label :price %>
          <%= f.number_field :price, class: 'form-control' %>
        </div>

        <div class="mb-3">
          <%= f.label :quantity %>
          <%= f.number_field :quantity, class: 'form-control' %>
        </div>

        <div class="mb-3">
          <%= f.submit 'Create Food', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</main>

app/views/home/index.html.erb
<main class="main">
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">
          Welcome 
          <% if current_user.present? %>
            <%= current_user.name %>!
          <% else %>
            to the Recipe App!
          <% end %>
        </h1>
        <p class="lead text-muted">Discover Delicious Recipes: A Culinary Journey Awaits!</p>
        <p>
          <a href="<%= foods_path %>" class="btn btn-primary my-2">Foods</a>
          <a href="<%= public_recipes_path %>" class="btn btn-secondary my-2">Recipes</a>
        </p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

        <% @foods.each do |food| %>
          <div class="col">
            <div class="card shadow-sm">

              <div class="card-body">
                <p class="card-text">
                  <%= link_to food.name, public_recipes_path, class: "text-capitalize text-decoration-none"  %>
                </p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                  </div>
                  <small class="text-muted">9 mins</small>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodRecipe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="header">
      <%= render "shared/navbar" %>
    </header>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

app/views/public_recipes/index.html.erb
<div class="container mt-5">
  <div class="col-12 text-center">
    <h1 class="text text-primary">Public Recipes</h1>
  </div>
  <% @recipes.includes(:user).each do |recipe| %>
    <div class="card mb-5">
      <div class="card-body">
        <div class="row">
          <div class="col-4" style="display:flex;flex-direction:column;">
            <%= link_to recipe_path(recipe), class: "text-decoration-none" do %>
              <h3><%= recipe.name %></h3>
              <span class="text-primary">By: <%= recipe.user.name %></span>
            <% end %>
          </div>
          <div class="col-8">
            <p>
              Total food items: <%= recipe.recipe_foods.count %>
            </p>
            <p>
              Total price: &#x20b9; <%= number_to_currency(recipe.recipe_foods.sum { |rf| rf.food.price * rf.quantity }, unit: '') %>
            </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/recipe_foods/new.html.erb
<section class="container-sm">
  <div class="recipe-food-section flex justify-center items-center">
    <div class="recipe-food-container">
      <h2 class="text-2xl font-semibold">
        Add ingredients for 
        <span class="text text-primary small"><%= @recipe.name %></span>
      </h2>

      <div class="recipe-food-form-container mt-5 border p-5">
        <%= form_with model: [@recipe, @recipe_food], class: "needs-validation", novalidate: true do |f|%>
          <div class="form-group mb-5">
            <%= f.collection_select :food_id, Food.order(:name), :id, :name_with_measurement_unit, { prompt: "--Select Ingredients--" }, class: "form-control" %>
          </div>

          <div class="form-group mb-5">
            <%= f.number_field :quantity, placeholder: 'Quantity', required: true, step: '0.01', class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.submit "Add New Ingredient", class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/recipes/index.html.erb
<div class="container mt-5">
  <%= link_to "Add Recipe", new_recipe_path, class: "btn btn-primary mb-3" %>
  <% @recipes.each do |recipe| %>
    <div class="card mb-5">
      <div class="card-body">
        <article class="col-12 row">
          <div class="col-4" style="display:flex;flex-direction:column;align-items: center;">
            
            <%= link_to recipe_path(recipe), class: "btn btn-link text-decoration-none mb-2" do %>
              <h1><%= recipe.name %></h1>
            <% end %>

            <%= button_to "REMOVE", recipe_path(recipe), method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-outline-danger' %>
          </div>
          <div class="col-8">
            <p>
              <%= recipe.description %>
            </p>
          </div>
        </article>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<div class="container mt-5">
  <h2>Add New Recipe</h2>

  <%= form_with(model: @recipe, url: recipes_path, method: :post, html: { class: "row g-3" }) do |form| %>
    <div class="col-md-6">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control", required: true %>
    </div>

    <div class="col-md-6 p-4 justify-content-center d-flex">
      <div class="form-check form-switch">
        <%= form.label :public, class: "form-check-label" %>
        <%= form.check_box :public, class: "form-check-input" %>
      </div>
    </div>

    <div class="col-md-12">
      <%= form.label :description, class: "form-label" %>
      <%= form.text_area :description, class: "form-control", required: true %>
    </div>

    <div class="col-md-3">
      <%= form.label :preparation_time_hr, class: "form-label" %>
      <%= form.number_field :preparation_time_hr, class: "form-control", min: 0 %>
    </div>

    <div class="col-md-3">
      <%= form.label :preparation_time_min, class: "form-label" %>
      <%= form.number_field :preparation_time_min, class: "form-control", min: 0, max: 59 %>
    </div>

    <div class="col-md-3">
      <%= form.label :cooking_time_hr, class: "form-label" %>
      <%= form.number_field :cooking_time_hr, class: "form-control", min: 0 %>
    </div>

    <div class="col-md-3">
      <%= form.label :cooking_time_min, class: "form-label" %>
      <%= form.number_field :cooking_time_min, class: "form-control", min: 0, max: 59 %>
    </div>

    <div class="col-md-2">
      <%= form.submit "Create Recipe", class: "btn btn-primary" %>
    </div>

    <div class="col-md-2">
      <%= link_to "Back to Recipes", recipes_path, class: "btn btn-secondary" %>
    </div>
    
  <% end %>
  
</div>

app/views/recipes/show.html.erb
<section class="container mt-5">
  <div class="row">
    <div class="card mb-3">
      <div class="card-body">

        <div class="col-12 text-center">
          <h1 class="text text-primary"><%= @recipe.name %></h1>
        </div>
        
        <div class="col-12 row p-5">
          <div class="col-8">            
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <h3 class="capitalize">Preparation time</h3>
                <div class="flex text-sm justify-content-evenly">
                  <% if @preparation_time_hours > 0 %>
                    <%= "#{@preparation_time_hours} hr" %>
                  <% end %>
                  <% if @preparation_time_minutes > 0 %>
                    <%= "#{@preparation_time_minutes} min" %>
                  <% end %>
                </div>
              </li>
              <li class="list-group-item">
                <h3 class="capitalize">Cooking time</h3>
                <div class="flex text-sm justify-content-evenly">
                  <% if @cooking_time_hours > 0 %>
                    <%= "#{@cooking_time_hours} hr" %>
                  <% end %>
                  <% if @cooking_time_minutes > 0 %>
                    <%= "#{@cooking_time_minutes} min" %>
                  <% end %>
                </div>
              </li>
              <li class="list-group-item">
                <%= @recipe.description %>
              </li>
            </ul>
          </div>

          <div class="col-4 justify-content-center" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-trigger="hover" title="Click on text to update">
            <% if current_user == @recipe.user %>
              <div class="form-group d-flex gap-3 align-items-center form-check form-switch">
                <%= button_to "#{@recipe.public ? 'Private' : 'Public'}", toggle_public_recipe_path(@recipe), method: :patch,
                  class: "btn btn-link link-offset-2 link-underline link-underline-opacity-0" %>
                <%= button_tag type: 'submit', class: "btn" do %>
                  <input type="checkbox" name="recipe[public]" class="form-check-input" disabled <%= 'checked' if @recipe.public? %>>
                <% end %>
              </div>
            <% end %>
          </div>

          <div class="col-12 p-3 mt-2">
            <div class="d-flex justify-content-between">
              <%= link_to "Generate shopping List", generate_shopping_lists_path(recipe_id: @recipe.id), class: 'btn btn-primary' %>
              <%= link_to "Add ingredient", new_recipe_recipe_food_path(@recipe.id), class: 'btn btn-primary mr-2' %>
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="card">
      <div class="card-body">          
        <table class="table table-bordered table-hover">
          <thead class="table-primary">
            <tr>
              <th>Food</th>
              <th>Quantity</th>
              <th>Value</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @recipe.recipe_foods.each do |recipe_food| %>
              <tr>
                <th><%= recipe_food.food.name %></th>
                <th><%= recipe_food.quantity %></th>
                <th><%= recipe_food.total_price %></th>
                <th>
                  <%= button_to 'Delete', recipe_recipe_food_path(recipe_id: @recipe.id, id: recipe_food.id), method: :delete, class: 'btn btn-danger btn-sm',
                  data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
                </th>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary justify-content-center">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Foods Recipe</a>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Foods", foods_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Recipes", recipes_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Public Recipes", public_recipes_path, class: "nav-link" %>
        </li>
      </ul>
      <span class="navbar-text mr-5">
        <% if current_user.present? %>
          <div class="nav-item dropstart">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" class="row">             
              
                Hi <%= current_user.name%>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li>
                <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete, confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, class: "dropdown-item bg-primary" %>
              </li>
            </ul>
          </div>

        <% else %>
          <%= link_to "Login", new_user_session_path, class: "btn btn-link" %>
        <% end %>
        
      </span>
    </div>
  </div>
</nav>

app/views/shopping_lists/index.html.erb
<div class="container mt-5">
  <div class="col-12 text-center">
    <h1 class="text text-primary">Shopping List</h1>
  </div>
  <div class="card mb-5">
    <div class="card-body">
      <div class="d-flex justify-content-between mb-5 mt-3">
        <label class="text text-primary">Amount of food items to buy: <%= @recipe_foods&.count || 0 %></label>
        <label class="text text-primary">Total value of food needed: <%= number_to_currency(@needed_money, precision: 2) %></label>
      </div>
      <div>
        <table class="table table-bordered table-hover">
          <thead class="table-primary">
            <tr>
              <th>Food</th>
              <th>Quantity</th>
              <th>Value</th>
            </tr>
          </thead>
          <tbody>
            <% @recipe_foods&.each do |recipe_food| %>
              <tr>
                <td><%= recipe_food.food.name %></td>
                <td><%= recipe_food.quantity %></td>
                <td><%= number_to_currency(recipe_food.food.price * recipe_food.quantity, unit: '') %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>